### ISSUE TITLE
Send button disappears when typing only emoji

### ISSUE THREAD

**Issue by danikkm** [haoict/messenger-no-ads#1]
When you type emoji in message box, send arrow just disappears.
Here proof: ![image](https://user-images.githubusercontent.com/40919040/79339998-66eb2400-7f32-11ea-81ee-105e1050e1e1.jpeg)

One more thing, textbox resizes when you switch from keyboard to stickers.

**Comment by haoict** [comment]
Hi, Thank you for the issue report.
It is fixed on new version (1.1.2). Please check it and update status here.

**Comment by danikkm** [comment]
Thanks, seems to be working as it should :)
