### ISSUE TITLE
Crashes during the audio call

### ISSUE THREAD

**Issue by danikkm** [haoict/messenger-no-ads#10]
Messenger crashes after you tap on “open chat” on your lock screen only during the call

**Comment by haoict** [comment]
Just tried to reproduce on my phone but it's fine.
Could you provide more information on how to reproduce the issue.
And also your iphone model, ios version, messenger version and tweak version. Thanks :)

**Comment by danikkm** [comment]
It seems there is a problem with another tweak: Prysm, I’ve downloaded cr4shed and managed to capture the crashlog. ![image](https://user-images.githubusercontent.com/40919040/80111864-1c4c5600-8589-11ea-8133-d232ac5461b6.png)

It happens when I’m on speaker phone, trying to press this button: ![image](https://user-images.githubusercontent.com/40919040/80111942-325a1680-8589-11ea-9c85-6ce6ba540034.jpeg)

Maybe you can contact the dev and mention this issue or there is an issue with Prysm?

**Comment by danikkm** [comment]
Yeah, forgot to mention.
iOS 13.3, iPhone Xs Max, Messenger v261.1, latest v2.5.0 Messenger tweak and Prysm v1.7.4

**Comment by haoict** [comment]
I don't have Prysm installed, could you help me this:
1. Disable (or uninstall) Messenger No Ads, keep Prysm and reproduce the bug. If it crashes, then it is a bug from Prysm, not mine.
2. If above step doesn't crash, disable Prysm, keep Messenger No Ads and reproduce the bug.
Let me know the result. Thanks a lot.

**Comment by danikkm** [comment]
Yeah, it appears that there is a problem with Prysm. 

Thank you for your time. Good job on that tweak, keep it that way 😉

**Comment by haoict** [comment]
@danikkm Thanks for you support <3
