### ISSUE TITLE
Improve the release process

### ISSUE THREAD

**Issue by Mikaz-fr** [haoict/messenger-no-ads#12]
Great tweak, working perfectly.

I think the release process could be improved though so users have an easier way to know what change in each version.
I believe it would make sense to:

- Create a release on this github before any new version is published
- Have a changelog on the tweak page so users know what is coming, especially if those changes require them to take action

For example settings moved location and new options got enabled by default in the past. This is highly disrupting changes for a user and they are deliver without any warning. You can't expect everybody to make research on reddit to find out that something changed in one of the tweak they just updated and now (for example) notifications aren't cleared anymore.

The code is great, but in my opinion the releasing method can become even better.

Thanks for your hard work.

**Comment by haoict** [comment]
That's good, I should follow it earlier :D 
Thanks for your suggestion and support
