### ISSUE TITLE
Lỗi messenger bị crash 

### ISSUE THREAD

**Issue by ljay9x** [haoict/messenger-no-ads#15]
Ip6s plus đang su dụng bản messenger mới nhất + tweak mess no ads 3.5.0: bị crash khi nhấn vào nút 3 chấm (...) ở story bạn bè, save hình không được và bị crash .
thanks

**Comment by haoict** [comment]
Hi @ljay9x 
The issue should be fixed in tweak version 3.6.0
https://github.com/haoict/messenger-no-ads/releases/tag/v3.6.0
