### ISSUE TITLE
Disable Story Seen Receipt & Can Save Friend’s Story doesn’t work with Messenger v300.0

### ISSUE THREAD

**Issue by davidkh88** [haoict/messenger-no-ads#28]
I saw you just pushed an update to v3.9.0 that fixed Disable Read Receipt with the app latest version (v300.0) but unfortunately this update caused the other features (mentioned in title) not to work with the latest version of Messenger.

**Comment by haoict** [comment]
Updated the tweak to v3.9.1. Please check. Thanks!
