### ISSUE TITLE
The latest update to Messenger

### ISSUE THREAD

**Issue by Skilatchix** [haoict/messenger-no-ads#31]
The latest update of Messenger does not fully work with the tweak

**Comment by haoict** [comment]
which feature is not working?

**Comment by Skilatchix** [comment]
![image](https://user-images.githubusercontent.com/42456946/110883036-21baa800-82e3-11eb-8bbe-da9d6029a849.jpeg)

The eye button is no longer displayed

**Comment by Skilatchix** [comment]
> which feature is not working?


The eye button is no longer displayed

**Comment by haoict** [comment]
Updated, please check:
https://github.com/haoict/messenger-no-ads/releases/tag/v3.10.0
