### ISSUE TITLE
Spam box disappeared 

### ISSUE THREAD

**Issue by Nadjibg** [haoict/messenger-no-ads#6]
Unfortunately the spam box bug still there !

**Comment by haoict** [comment]
This is not reproducible in my side.
Could you provide your device name, your current ios version, messenger version and tweak version?

**Comment by Nadjibg** [comment]
iPhone xr
13.3
2.1.0
260.2

أُرسلت من الـ iPhone

‫في 21‏/04‏/2020 الساعة 11:03، كتب/كتبت ‏Nguyen Van Hao ‏<notifications@github.com>:‬

﻿

This is not reproducible in my side.
Could you provide your device name, your current ios version, messenger version and tweak version?

**Comment by haoict** [comment]
@Nadjibg 
Hi man, I finally managed to work on the fix.
Please update to latest version 2.5.1 and check
Thanks!

**Comment by Nadjibg** [comment]
Yes, I can confirm!
It’s working

Thank you so much

أُرسلت من الـ iPhone

‫في 25‏/04‏/2020 الساعة 19:01، كتب/كتبت ‏Nguyen Van Hao ‏<notifications@github.com>:‬

﻿

Closed #6<https://github.com/haoict/messenger-no-ads/issues/6>.
