### ISSUE TITLE
Text not fully showing on iPad settings

### ISSUE THREAD

**Issue by nigiriemoji** [haoict/messenger-no-ads#7]
![C228EE6F-BE83-4CEA-9590-92DCD9CCEACE](https://user-images.githubusercontent.com/53108354/79699530-ef283c80-8244-11ea-8d64-6c9f3e5f42d6.png)

iPad Pro 10.5 13.4.1 checkra1n

**Comment by haoict** [comment]
This is fixed on latest version 2.2.0. 
Thanks
