### ISSUE TITLE
Phần reply tin nhắn ở messenger không thể phản hồi

### ISSUE THREAD

**Issue by Manhha3010** [haoict/messenger-no-ads#8]
Mình không ther phản hổi tin nhắn

**Comment by haoict** [comment]
Đã xác nhận.
Nếu bạn thực sự cần phản hồi tin nhắn thì hãy tắt tạm "Ẩn khi đang gõ" đi nhé. Mình sẽ tìm cách fix

**Comment by haoict** [comment]
https://github.com/haoict/messenger-no-ads/issues/5
